// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.19.4
// source: proto/coordinator.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SetEntryPrepareRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
}

func (x *SetEntryPrepareRequest) Reset() {
	*x = SetEntryPrepareRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_coordinator_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetEntryPrepareRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetEntryPrepareRequest) ProtoMessage() {}

func (x *SetEntryPrepareRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_coordinator_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetEntryPrepareRequest.ProtoReflect.Descriptor instead.
func (*SetEntryPrepareRequest) Descriptor() ([]byte, []int) {
	return file_proto_coordinator_proto_rawDescGZIP(), []int{0}
}

func (x *SetEntryPrepareRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type SetEntryPrepareResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *SetEntryPrepareResponse) Reset() {
	*x = SetEntryPrepareResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_coordinator_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetEntryPrepareResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetEntryPrepareResponse) ProtoMessage() {}

func (x *SetEntryPrepareResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_coordinator_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetEntryPrepareResponse.ProtoReflect.Descriptor instead.
func (*SetEntryPrepareResponse) Descriptor() ([]byte, []int) {
	return file_proto_coordinator_proto_rawDescGZIP(), []int{1}
}

type SetEntryCommitRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key   string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Field string `protobuf:"bytes,2,opt,name=field,proto3" json:"field,omitempty"`
	Value string `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *SetEntryCommitRequest) Reset() {
	*x = SetEntryCommitRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_coordinator_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetEntryCommitRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetEntryCommitRequest) ProtoMessage() {}

func (x *SetEntryCommitRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_coordinator_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetEntryCommitRequest.ProtoReflect.Descriptor instead.
func (*SetEntryCommitRequest) Descriptor() ([]byte, []int) {
	return file_proto_coordinator_proto_rawDescGZIP(), []int{2}
}

func (x *SetEntryCommitRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *SetEntryCommitRequest) GetField() string {
	if x != nil {
		return x.Field
	}
	return ""
}

func (x *SetEntryCommitRequest) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type SetEntryCommitResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *SetEntryCommitResponse) Reset() {
	*x = SetEntryCommitResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_coordinator_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetEntryCommitResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetEntryCommitResponse) ProtoMessage() {}

func (x *SetEntryCommitResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_coordinator_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetEntryCommitResponse.ProtoReflect.Descriptor instead.
func (*SetEntryCommitResponse) Descriptor() ([]byte, []int) {
	return file_proto_coordinator_proto_rawDescGZIP(), []int{3}
}

type GetEntryByIdRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *GetEntryByIdRequest) Reset() {
	*x = GetEntryByIdRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_coordinator_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetEntryByIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEntryByIdRequest) ProtoMessage() {}

func (x *GetEntryByIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_coordinator_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEntryByIdRequest.ProtoReflect.Descriptor instead.
func (*GetEntryByIdRequest) Descriptor() ([]byte, []int) {
	return file_proto_coordinator_proto_rawDescGZIP(), []int{4}
}

func (x *GetEntryByIdRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetEntryByIdResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Entry string `protobuf:"bytes,1,opt,name=entry,proto3" json:"entry,omitempty"`
}

func (x *GetEntryByIdResponse) Reset() {
	*x = GetEntryByIdResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_coordinator_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetEntryByIdResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEntryByIdResponse) ProtoMessage() {}

func (x *GetEntryByIdResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_coordinator_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEntryByIdResponse.ProtoReflect.Descriptor instead.
func (*GetEntryByIdResponse) Descriptor() ([]byte, []int) {
	return file_proto_coordinator_proto_rawDescGZIP(), []int{5}
}

func (x *GetEntryByIdResponse) GetEntry() string {
	if x != nil {
		return x.Entry
	}
	return ""
}

// For retrieving the id of a row using an indexed field.
type GetEntryByFieldRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Field string `protobuf:"bytes,1,opt,name=field,proto3" json:"field,omitempty"`
	Key   string `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
}

func (x *GetEntryByFieldRequest) Reset() {
	*x = GetEntryByFieldRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_coordinator_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetEntryByFieldRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEntryByFieldRequest) ProtoMessage() {}

func (x *GetEntryByFieldRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_coordinator_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEntryByFieldRequest.ProtoReflect.Descriptor instead.
func (*GetEntryByFieldRequest) Descriptor() ([]byte, []int) {
	return file_proto_coordinator_proto_rawDescGZIP(), []int{6}
}

func (x *GetEntryByFieldRequest) GetField() string {
	if x != nil {
		return x.Field
	}
	return ""
}

func (x *GetEntryByFieldRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type GetEntryByFieldResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Entry string `protobuf:"bytes,1,opt,name=entry,proto3" json:"entry,omitempty"`
}

func (x *GetEntryByFieldResponse) Reset() {
	*x = GetEntryByFieldResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_coordinator_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetEntryByFieldResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEntryByFieldResponse) ProtoMessage() {}

func (x *GetEntryByFieldResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_coordinator_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEntryByFieldResponse.ProtoReflect.Descriptor instead.
func (*GetEntryByFieldResponse) Descriptor() ([]byte, []int) {
	return file_proto_coordinator_proto_rawDescGZIP(), []int{7}
}

func (x *GetEntryByFieldResponse) GetEntry() string {
	if x != nil {
		return x.Entry
	}
	return ""
}

var File_proto_coordinator_proto protoreflect.FileDescriptor

var file_proto_coordinator_proto_rawDesc = []byte{
	0x0a, 0x17, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x63, 0x6f, 0x6f, 0x72, 0x64, 0x69, 0x6e, 0x61,
	0x74, 0x6f, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0b, 0x63, 0x6f, 0x6f, 0x72, 0x64,
	0x69, 0x6e, 0x61, 0x74, 0x6f, 0x72, 0x22, 0x2a, 0x0a, 0x16, 0x53, 0x65, 0x74, 0x45, 0x6e, 0x74,
	0x72, 0x79, 0x50, 0x72, 0x65, 0x70, 0x61, 0x72, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b,
	0x65, 0x79, 0x22, 0x19, 0x0a, 0x17, 0x53, 0x65, 0x74, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x50, 0x72,
	0x65, 0x70, 0x61, 0x72, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x55, 0x0a,
	0x15, 0x53, 0x65, 0x74, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x43, 0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x66, 0x69, 0x65, 0x6c,
	0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x12, 0x14,
	0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76,
	0x61, 0x6c, 0x75, 0x65, 0x22, 0x18, 0x0a, 0x16, 0x53, 0x65, 0x74, 0x45, 0x6e, 0x74, 0x72, 0x79,
	0x43, 0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x25,
	0x0a, 0x13, 0x47, 0x65, 0x74, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x42, 0x79, 0x49, 0x64, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x2c, 0x0a, 0x14, 0x47, 0x65, 0x74, 0x45, 0x6e, 0x74, 0x72,
	0x79, 0x42, 0x79, 0x49, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x14, 0x0a,
	0x05, 0x65, 0x6e, 0x74, 0x72, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x6e,
	0x74, 0x72, 0x79, 0x22, 0x40, 0x0a, 0x16, 0x47, 0x65, 0x74, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x42,
	0x79, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a,
	0x05, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x66, 0x69,
	0x65, 0x6c, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x03, 0x6b, 0x65, 0x79, 0x22, 0x2f, 0x0a, 0x17, 0x47, 0x65, 0x74, 0x45, 0x6e, 0x74, 0x72,
	0x79, 0x42, 0x79, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x14, 0x0a, 0x05, 0x65, 0x6e, 0x74, 0x72, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x05, 0x65, 0x6e, 0x74, 0x72, 0x79, 0x42, 0x19, 0x5a, 0x17, 0x4a, 0x4b, 0x5a, 0x44, 0x42, 0x2f,
	0x43, 0x6f, 0x6f, 0x72, 0x64, 0x69, 0x6e, 0x61, 0x74, 0x6f, 0x72, 0x2f, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_coordinator_proto_rawDescOnce sync.Once
	file_proto_coordinator_proto_rawDescData = file_proto_coordinator_proto_rawDesc
)

func file_proto_coordinator_proto_rawDescGZIP() []byte {
	file_proto_coordinator_proto_rawDescOnce.Do(func() {
		file_proto_coordinator_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_coordinator_proto_rawDescData)
	})
	return file_proto_coordinator_proto_rawDescData
}

var file_proto_coordinator_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_proto_coordinator_proto_goTypes = []interface{}{
	(*SetEntryPrepareRequest)(nil),  // 0: coordinator.SetEntryPrepareRequest
	(*SetEntryPrepareResponse)(nil), // 1: coordinator.SetEntryPrepareResponse
	(*SetEntryCommitRequest)(nil),   // 2: coordinator.SetEntryCommitRequest
	(*SetEntryCommitResponse)(nil),  // 3: coordinator.SetEntryCommitResponse
	(*GetEntryByIdRequest)(nil),     // 4: coordinator.GetEntryByIdRequest
	(*GetEntryByIdResponse)(nil),    // 5: coordinator.GetEntryByIdResponse
	(*GetEntryByFieldRequest)(nil),  // 6: coordinator.GetEntryByFieldRequest
	(*GetEntryByFieldResponse)(nil), // 7: coordinator.GetEntryByFieldResponse
}
var file_proto_coordinator_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_coordinator_proto_init() }
func file_proto_coordinator_proto_init() {
	if File_proto_coordinator_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_coordinator_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetEntryPrepareRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_coordinator_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetEntryPrepareResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_coordinator_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetEntryCommitRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_coordinator_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetEntryCommitResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_coordinator_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetEntryByIdRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_coordinator_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetEntryByIdResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_coordinator_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetEntryByFieldRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_coordinator_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetEntryByFieldResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_coordinator_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_coordinator_proto_goTypes,
		DependencyIndexes: file_proto_coordinator_proto_depIdxs,
		MessageInfos:      file_proto_coordinator_proto_msgTypes,
	}.Build()
	File_proto_coordinator_proto = out.File
	file_proto_coordinator_proto_rawDesc = nil
	file_proto_coordinator_proto_goTypes = nil
	file_proto_coordinator_proto_depIdxs = nil
}
