// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.19.4
// source: db/proto/db.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UpdateMap struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Updates map[string]string `protobuf:"bytes,1,rep,name=updates,proto3" json:"updates,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Unique  bool              `protobuf:"varint,2,opt,name=unique,proto3" json:"unique,omitempty"`
}

func (x *UpdateMap) Reset() {
	*x = UpdateMap{}
	if protoimpl.UnsafeEnabled {
		mi := &file_db_proto_db_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateMap) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateMap) ProtoMessage() {}

func (x *UpdateMap) ProtoReflect() protoreflect.Message {
	mi := &file_db_proto_db_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateMap.ProtoReflect.Descriptor instead.
func (*UpdateMap) Descriptor() ([]byte, []int) {
	return file_db_proto_db_proto_rawDescGZIP(), []int{0}
}

func (x *UpdateMap) GetUpdates() map[string]string {
	if x != nil {
		return x.Updates
	}
	return nil
}

func (x *UpdateMap) GetUnique() bool {
	if x != nil {
		return x.Unique
	}
	return false
}

type SetEntryPrepareRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IdempotencyKey int64             `protobuf:"varint,1,opt,name=idempotencyKey,proto3" json:"idempotencyKey,omitempty"`
	Key            string            `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	Updates        map[string]string `protobuf:"bytes,3,rep,name=updates,proto3" json:"updates,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Unique         bool              `protobuf:"varint,4,opt,name=unique,proto3" json:"unique,omitempty"`
}

func (x *SetEntryPrepareRequest) Reset() {
	*x = SetEntryPrepareRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_db_proto_db_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetEntryPrepareRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetEntryPrepareRequest) ProtoMessage() {}

func (x *SetEntryPrepareRequest) ProtoReflect() protoreflect.Message {
	mi := &file_db_proto_db_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetEntryPrepareRequest.ProtoReflect.Descriptor instead.
func (*SetEntryPrepareRequest) Descriptor() ([]byte, []int) {
	return file_db_proto_db_proto_rawDescGZIP(), []int{1}
}

func (x *SetEntryPrepareRequest) GetIdempotencyKey() int64 {
	if x != nil {
		return x.IdempotencyKey
	}
	return 0
}

func (x *SetEntryPrepareRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *SetEntryPrepareRequest) GetUpdates() map[string]string {
	if x != nil {
		return x.Updates
	}
	return nil
}

func (x *SetEntryPrepareRequest) GetUnique() bool {
	if x != nil {
		return x.Unique
	}
	return false
}

type SetEntryPrepareResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *SetEntryPrepareResponse) Reset() {
	*x = SetEntryPrepareResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_db_proto_db_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetEntryPrepareResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetEntryPrepareResponse) ProtoMessage() {}

func (x *SetEntryPrepareResponse) ProtoReflect() protoreflect.Message {
	mi := &file_db_proto_db_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetEntryPrepareResponse.ProtoReflect.Descriptor instead.
func (*SetEntryPrepareResponse) Descriptor() ([]byte, []int) {
	return file_db_proto_db_proto_rawDescGZIP(), []int{2}
}

type SetEntryCommitRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IdempotencyKey int64             `protobuf:"varint,1,opt,name=idempotencyKey,proto3" json:"idempotencyKey,omitempty"`
	Key            string            `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	Updates        map[string]string `protobuf:"bytes,3,rep,name=updates,proto3" json:"updates,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Unique         bool              `protobuf:"varint,4,opt,name=unique,proto3" json:"unique,omitempty"`
}

func (x *SetEntryCommitRequest) Reset() {
	*x = SetEntryCommitRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_db_proto_db_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetEntryCommitRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetEntryCommitRequest) ProtoMessage() {}

func (x *SetEntryCommitRequest) ProtoReflect() protoreflect.Message {
	mi := &file_db_proto_db_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetEntryCommitRequest.ProtoReflect.Descriptor instead.
func (*SetEntryCommitRequest) Descriptor() ([]byte, []int) {
	return file_db_proto_db_proto_rawDescGZIP(), []int{3}
}

func (x *SetEntryCommitRequest) GetIdempotencyKey() int64 {
	if x != nil {
		return x.IdempotencyKey
	}
	return 0
}

func (x *SetEntryCommitRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *SetEntryCommitRequest) GetUpdates() map[string]string {
	if x != nil {
		return x.Updates
	}
	return nil
}

func (x *SetEntryCommitRequest) GetUnique() bool {
	if x != nil {
		return x.Unique
	}
	return false
}

type SetEntryCommitResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *SetEntryCommitResponse) Reset() {
	*x = SetEntryCommitResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_db_proto_db_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetEntryCommitResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetEntryCommitResponse) ProtoMessage() {}

func (x *SetEntryCommitResponse) ProtoReflect() protoreflect.Message {
	mi := &file_db_proto_db_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetEntryCommitResponse.ProtoReflect.Descriptor instead.
func (*SetEntryCommitResponse) Descriptor() ([]byte, []int) {
	return file_db_proto_db_proto_rawDescGZIP(), []int{4}
}

type SetEntryAbortRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IdempotencyKey int64 `protobuf:"varint,1,opt,name=idempotencyKey,proto3" json:"idempotencyKey,omitempty"`
	Unique         bool  `protobuf:"varint,2,opt,name=unique,proto3" json:"unique,omitempty"`
}

func (x *SetEntryAbortRequest) Reset() {
	*x = SetEntryAbortRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_db_proto_db_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetEntryAbortRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetEntryAbortRequest) ProtoMessage() {}

func (x *SetEntryAbortRequest) ProtoReflect() protoreflect.Message {
	mi := &file_db_proto_db_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetEntryAbortRequest.ProtoReflect.Descriptor instead.
func (*SetEntryAbortRequest) Descriptor() ([]byte, []int) {
	return file_db_proto_db_proto_rawDescGZIP(), []int{5}
}

func (x *SetEntryAbortRequest) GetIdempotencyKey() int64 {
	if x != nil {
		return x.IdempotencyKey
	}
	return 0
}

func (x *SetEntryAbortRequest) GetUnique() bool {
	if x != nil {
		return x.Unique
	}
	return false
}

type SetEntryAbortResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *SetEntryAbortResponse) Reset() {
	*x = SetEntryAbortResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_db_proto_db_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetEntryAbortResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetEntryAbortResponse) ProtoMessage() {}

func (x *SetEntryAbortResponse) ProtoReflect() protoreflect.Message {
	mi := &file_db_proto_db_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetEntryAbortResponse.ProtoReflect.Descriptor instead.
func (*SetEntryAbortResponse) Descriptor() ([]byte, []int) {
	return file_db_proto_db_proto_rawDescGZIP(), []int{6}
}

type SetEntryPrepareBatchRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IdempotencyKey int64        `protobuf:"varint,1,opt,name=idempotencyKey,proto3" json:"idempotencyKey,omitempty"`
	Keys           []string     `protobuf:"bytes,2,rep,name=keys,proto3" json:"keys,omitempty"`
	Updates        []*UpdateMap `protobuf:"bytes,3,rep,name=updates,proto3" json:"updates,omitempty"`
}

func (x *SetEntryPrepareBatchRequest) Reset() {
	*x = SetEntryPrepareBatchRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_db_proto_db_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetEntryPrepareBatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetEntryPrepareBatchRequest) ProtoMessage() {}

func (x *SetEntryPrepareBatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_db_proto_db_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetEntryPrepareBatchRequest.ProtoReflect.Descriptor instead.
func (*SetEntryPrepareBatchRequest) Descriptor() ([]byte, []int) {
	return file_db_proto_db_proto_rawDescGZIP(), []int{7}
}

func (x *SetEntryPrepareBatchRequest) GetIdempotencyKey() int64 {
	if x != nil {
		return x.IdempotencyKey
	}
	return 0
}

func (x *SetEntryPrepareBatchRequest) GetKeys() []string {
	if x != nil {
		return x.Keys
	}
	return nil
}

func (x *SetEntryPrepareBatchRequest) GetUpdates() []*UpdateMap {
	if x != nil {
		return x.Updates
	}
	return nil
}

type SetEntryPrepareBatchResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *SetEntryPrepareBatchResponse) Reset() {
	*x = SetEntryPrepareBatchResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_db_proto_db_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetEntryPrepareBatchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetEntryPrepareBatchResponse) ProtoMessage() {}

func (x *SetEntryPrepareBatchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_db_proto_db_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetEntryPrepareBatchResponse.ProtoReflect.Descriptor instead.
func (*SetEntryPrepareBatchResponse) Descriptor() ([]byte, []int) {
	return file_db_proto_db_proto_rawDescGZIP(), []int{8}
}

type SetEntryCommitBatchRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IdempotencyKey int64        `protobuf:"varint,1,opt,name=idempotencyKey,proto3" json:"idempotencyKey,omitempty"`
	Keys           []string     `protobuf:"bytes,2,rep,name=keys,proto3" json:"keys,omitempty"`
	Updates        []*UpdateMap `protobuf:"bytes,3,rep,name=updates,proto3" json:"updates,omitempty"`
}

func (x *SetEntryCommitBatchRequest) Reset() {
	*x = SetEntryCommitBatchRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_db_proto_db_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetEntryCommitBatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetEntryCommitBatchRequest) ProtoMessage() {}

func (x *SetEntryCommitBatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_db_proto_db_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetEntryCommitBatchRequest.ProtoReflect.Descriptor instead.
func (*SetEntryCommitBatchRequest) Descriptor() ([]byte, []int) {
	return file_db_proto_db_proto_rawDescGZIP(), []int{9}
}

func (x *SetEntryCommitBatchRequest) GetIdempotencyKey() int64 {
	if x != nil {
		return x.IdempotencyKey
	}
	return 0
}

func (x *SetEntryCommitBatchRequest) GetKeys() []string {
	if x != nil {
		return x.Keys
	}
	return nil
}

func (x *SetEntryCommitBatchRequest) GetUpdates() []*UpdateMap {
	if x != nil {
		return x.Updates
	}
	return nil
}

type SetEntryCommitBatchResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *SetEntryCommitBatchResponse) Reset() {
	*x = SetEntryCommitBatchResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_db_proto_db_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetEntryCommitBatchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetEntryCommitBatchResponse) ProtoMessage() {}

func (x *SetEntryCommitBatchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_db_proto_db_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetEntryCommitBatchResponse.ProtoReflect.Descriptor instead.
func (*SetEntryCommitBatchResponse) Descriptor() ([]byte, []int) {
	return file_db_proto_db_proto_rawDescGZIP(), []int{10}
}

type SetEntryAbortBatchRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IdempotencyKey int64 `protobuf:"varint,1,opt,name=idempotencyKey,proto3" json:"idempotencyKey,omitempty"`
}

func (x *SetEntryAbortBatchRequest) Reset() {
	*x = SetEntryAbortBatchRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_db_proto_db_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetEntryAbortBatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetEntryAbortBatchRequest) ProtoMessage() {}

func (x *SetEntryAbortBatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_db_proto_db_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetEntryAbortBatchRequest.ProtoReflect.Descriptor instead.
func (*SetEntryAbortBatchRequest) Descriptor() ([]byte, []int) {
	return file_db_proto_db_proto_rawDescGZIP(), []int{11}
}

func (x *SetEntryAbortBatchRequest) GetIdempotencyKey() int64 {
	if x != nil {
		return x.IdempotencyKey
	}
	return 0
}

type SetEntryAbortBatchResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *SetEntryAbortBatchResponse) Reset() {
	*x = SetEntryAbortBatchResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_db_proto_db_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetEntryAbortBatchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetEntryAbortBatchResponse) ProtoMessage() {}

func (x *SetEntryAbortBatchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_db_proto_db_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetEntryAbortBatchResponse.ProtoReflect.Descriptor instead.
func (*SetEntryAbortBatchResponse) Descriptor() ([]byte, []int) {
	return file_db_proto_db_proto_rawDescGZIP(), []int{12}
}

type GetEntryRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Query string  `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	Field *string `protobuf:"bytes,2,opt,name=field,proto3,oneof" json:"field,omitempty"`
}

func (x *GetEntryRequest) Reset() {
	*x = GetEntryRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_db_proto_db_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetEntryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEntryRequest) ProtoMessage() {}

func (x *GetEntryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_db_proto_db_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEntryRequest.ProtoReflect.Descriptor instead.
func (*GetEntryRequest) Descriptor() ([]byte, []int) {
	return file_db_proto_db_proto_rawDescGZIP(), []int{13}
}

func (x *GetEntryRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *GetEntryRequest) GetField() string {
	if x != nil && x.Field != nil {
		return *x.Field
	}
	return ""
}

type GetEntryResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Entry string `protobuf:"bytes,3,opt,name=entry,proto3" json:"entry,omitempty"`
}

func (x *GetEntryResponse) Reset() {
	*x = GetEntryResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_db_proto_db_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetEntryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEntryResponse) ProtoMessage() {}

func (x *GetEntryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_db_proto_db_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEntryResponse.ProtoReflect.Descriptor instead.
func (*GetEntryResponse) Descriptor() ([]byte, []int) {
	return file_db_proto_db_proto_rawDescGZIP(), []int{14}
}

func (x *GetEntryResponse) GetEntry() string {
	if x != nil {
		return x.Entry
	}
	return ""
}

var File_db_proto_db_proto protoreflect.FileDescriptor

var file_db_proto_db_proto_rawDesc = []byte{
	0x0a, 0x11, 0x64, 0x62, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x64, 0x62, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x02, 0x64, 0x62, 0x22, 0x95, 0x01, 0x0a, 0x09, 0x55, 0x70, 0x64, 0x61,
	0x74, 0x65, 0x4d, 0x61, 0x70, 0x12, 0x34, 0x0a, 0x07, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x73,
	0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x64, 0x62, 0x2e, 0x55, 0x70, 0x64, 0x61,
	0x74, 0x65, 0x4d, 0x61, 0x70, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x73, 0x45, 0x6e, 0x74,
	0x72, 0x79, 0x52, 0x07, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x75,
	0x6e, 0x69, 0x71, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x75, 0x6e, 0x69,
	0x71, 0x75, 0x65, 0x1a, 0x3a, 0x0a, 0x0c, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x73, 0x45, 0x6e,
	0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x22,
	0xe9, 0x01, 0x0a, 0x16, 0x53, 0x65, 0x74, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x50, 0x72, 0x65, 0x70,
	0x61, 0x72, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x26, 0x0a, 0x0e, 0x69, 0x64,
	0x65, 0x6d, 0x70, 0x6f, 0x74, 0x65, 0x6e, 0x63, 0x79, 0x4b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x0e, 0x69, 0x64, 0x65, 0x6d, 0x70, 0x6f, 0x74, 0x65, 0x6e, 0x63, 0x79, 0x4b,
	0x65, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x03, 0x6b, 0x65, 0x79, 0x12, 0x41, 0x0a, 0x07, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x73, 0x18,
	0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x27, 0x2e, 0x64, 0x62, 0x2e, 0x53, 0x65, 0x74, 0x45, 0x6e,
	0x74, 0x72, 0x79, 0x50, 0x72, 0x65, 0x70, 0x61, 0x72, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x07,
	0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x6e, 0x69, 0x71, 0x75,
	0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x75, 0x6e, 0x69, 0x71, 0x75, 0x65, 0x1a,
	0x3a, 0x0a, 0x0c, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12,
	0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65,
	0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x22, 0x19, 0x0a, 0x17, 0x53,
	0x65, 0x74, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x50, 0x72, 0x65, 0x70, 0x61, 0x72, 0x65, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0xe7, 0x01, 0x0a, 0x15, 0x53, 0x65, 0x74, 0x45, 0x6e,
	0x74, 0x72, 0x79, 0x43, 0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x26, 0x0a, 0x0e, 0x69, 0x64, 0x65, 0x6d, 0x70, 0x6f, 0x74, 0x65, 0x6e, 0x63, 0x79, 0x4b,
	0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0e, 0x69, 0x64, 0x65, 0x6d, 0x70, 0x6f,
	0x74, 0x65, 0x6e, 0x63, 0x79, 0x4b, 0x65, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x40, 0x0a, 0x07, 0x75, 0x70,
	0x64, 0x61, 0x74, 0x65, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x26, 0x2e, 0x64, 0x62,
	0x2e, 0x53, 0x65, 0x74, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x43, 0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x73, 0x45, 0x6e,
	0x74, 0x72, 0x79, 0x52, 0x07, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x73, 0x12, 0x16, 0x0a, 0x06,
	0x75, 0x6e, 0x69, 0x71, 0x75, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x75, 0x6e,
	0x69, 0x71, 0x75, 0x65, 0x1a, 0x3a, 0x0a, 0x0c, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x73, 0x45,
	0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01,
	0x22, 0x18, 0x0a, 0x16, 0x53, 0x65, 0x74, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x43, 0x6f, 0x6d, 0x6d,
	0x69, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x56, 0x0a, 0x14, 0x53, 0x65,
	0x74, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x41, 0x62, 0x6f, 0x72, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x26, 0x0a, 0x0e, 0x69, 0x64, 0x65, 0x6d, 0x70, 0x6f, 0x74, 0x65, 0x6e, 0x63,
	0x79, 0x4b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0e, 0x69, 0x64, 0x65, 0x6d,
	0x70, 0x6f, 0x74, 0x65, 0x6e, 0x63, 0x79, 0x4b, 0x65, 0x79, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x6e,
	0x69, 0x71, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x75, 0x6e, 0x69, 0x71,
	0x75, 0x65, 0x22, 0x17, 0x0a, 0x15, 0x53, 0x65, 0x74, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x41, 0x62,
	0x6f, 0x72, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x82, 0x01, 0x0a, 0x1b,
	0x53, 0x65, 0x74, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x50, 0x72, 0x65, 0x70, 0x61, 0x72, 0x65, 0x42,
	0x61, 0x74, 0x63, 0x68, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x26, 0x0a, 0x0e, 0x69,
	0x64, 0x65, 0x6d, 0x70, 0x6f, 0x74, 0x65, 0x6e, 0x63, 0x79, 0x4b, 0x65, 0x79, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x0e, 0x69, 0x64, 0x65, 0x6d, 0x70, 0x6f, 0x74, 0x65, 0x6e, 0x63, 0x79,
	0x4b, 0x65, 0x79, 0x12, 0x12, 0x0a, 0x04, 0x6b, 0x65, 0x79, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28,
	0x09, 0x52, 0x04, 0x6b, 0x65, 0x79, 0x73, 0x12, 0x27, 0x0a, 0x07, 0x75, 0x70, 0x64, 0x61, 0x74,
	0x65, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x64, 0x62, 0x2e, 0x55, 0x70,
	0x64, 0x61, 0x74, 0x65, 0x4d, 0x61, 0x70, 0x52, 0x07, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x73,
	0x22, 0x1e, 0x0a, 0x1c, 0x53, 0x65, 0x74, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x50, 0x72, 0x65, 0x70,
	0x61, 0x72, 0x65, 0x42, 0x61, 0x74, 0x63, 0x68, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x22, 0x81, 0x01, 0x0a, 0x1a, 0x53, 0x65, 0x74, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x43, 0x6f, 0x6d,
	0x6d, 0x69, 0x74, 0x42, 0x61, 0x74, 0x63, 0x68, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x26, 0x0a, 0x0e, 0x69, 0x64, 0x65, 0x6d, 0x70, 0x6f, 0x74, 0x65, 0x6e, 0x63, 0x79, 0x4b, 0x65,
	0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0e, 0x69, 0x64, 0x65, 0x6d, 0x70, 0x6f, 0x74,
	0x65, 0x6e, 0x63, 0x79, 0x4b, 0x65, 0x79, 0x12, 0x12, 0x0a, 0x04, 0x6b, 0x65, 0x79, 0x73, 0x18,
	0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x04, 0x6b, 0x65, 0x79, 0x73, 0x12, 0x27, 0x0a, 0x07, 0x75,
	0x70, 0x64, 0x61, 0x74, 0x65, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x64,
	0x62, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x4d, 0x61, 0x70, 0x52, 0x07, 0x75, 0x70, 0x64,
	0x61, 0x74, 0x65, 0x73, 0x22, 0x1d, 0x0a, 0x1b, 0x53, 0x65, 0x74, 0x45, 0x6e, 0x74, 0x72, 0x79,
	0x43, 0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x42, 0x61, 0x74, 0x63, 0x68, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x22, 0x43, 0x0a, 0x19, 0x53, 0x65, 0x74, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x41,
	0x62, 0x6f, 0x72, 0x74, 0x42, 0x61, 0x74, 0x63, 0x68, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x26, 0x0a, 0x0e, 0x69, 0x64, 0x65, 0x6d, 0x70, 0x6f, 0x74, 0x65, 0x6e, 0x63, 0x79, 0x4b,
	0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0e, 0x69, 0x64, 0x65, 0x6d, 0x70, 0x6f,
	0x74, 0x65, 0x6e, 0x63, 0x79, 0x4b, 0x65, 0x79, 0x22, 0x1c, 0x0a, 0x1a, 0x53, 0x65, 0x74, 0x45,
	0x6e, 0x74, 0x72, 0x79, 0x41, 0x62, 0x6f, 0x72, 0x74, 0x42, 0x61, 0x74, 0x63, 0x68, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x4c, 0x0a, 0x0f, 0x47, 0x65, 0x74, 0x45, 0x6e, 0x74,
	0x72, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x71, 0x75, 0x65,
	0x72, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x71, 0x75, 0x65, 0x72, 0x79, 0x12,
	0x19, 0x0a, 0x05, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00,
	0x52, 0x05, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x88, 0x01, 0x01, 0x42, 0x08, 0x0a, 0x06, 0x5f, 0x66,
	0x69, 0x65, 0x6c, 0x64, 0x22, 0x28, 0x0a, 0x10, 0x47, 0x65, 0x74, 0x45, 0x6e, 0x74, 0x72, 0x79,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x6e, 0x74, 0x72,
	0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x6e, 0x74, 0x72, 0x79, 0x32, 0xa1,
	0x04, 0x0a, 0x05, 0x4a, 0x4b, 0x5a, 0x44, 0x42, 0x12, 0x4a, 0x0a, 0x0f, 0x53, 0x65, 0x74, 0x45,
	0x6e, 0x74, 0x72, 0x79, 0x50, 0x72, 0x65, 0x70, 0x61, 0x72, 0x65, 0x12, 0x1a, 0x2e, 0x64, 0x62,
	0x2e, 0x53, 0x65, 0x74, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x50, 0x72, 0x65, 0x70, 0x61, 0x72, 0x65,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1b, 0x2e, 0x64, 0x62, 0x2e, 0x53, 0x65, 0x74,
	0x45, 0x6e, 0x74, 0x72, 0x79, 0x50, 0x72, 0x65, 0x70, 0x61, 0x72, 0x65, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x59, 0x0a, 0x14, 0x53, 0x65, 0x74, 0x45, 0x6e, 0x74, 0x72, 0x79,
	0x50, 0x72, 0x65, 0x70, 0x61, 0x72, 0x65, 0x42, 0x61, 0x74, 0x63, 0x68, 0x12, 0x1f, 0x2e, 0x64,
	0x62, 0x2e, 0x53, 0x65, 0x74, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x50, 0x72, 0x65, 0x70, 0x61, 0x72,
	0x65, 0x42, 0x61, 0x74, 0x63, 0x68, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x20, 0x2e,
	0x64, 0x62, 0x2e, 0x53, 0x65, 0x74, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x50, 0x72, 0x65, 0x70, 0x61,
	0x72, 0x65, 0x42, 0x61, 0x74, 0x63, 0x68, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x47, 0x0a, 0x0e, 0x53, 0x65, 0x74, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x43, 0x6f, 0x6d, 0x6d, 0x69,
	0x74, 0x12, 0x19, 0x2e, 0x64, 0x62, 0x2e, 0x53, 0x65, 0x74, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x43,
	0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1a, 0x2e, 0x64,
	0x62, 0x2e, 0x53, 0x65, 0x74, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x43, 0x6f, 0x6d, 0x6d, 0x69, 0x74,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x56, 0x0a, 0x13, 0x53, 0x65, 0x74, 0x45,
	0x6e, 0x74, 0x72, 0x79, 0x43, 0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x42, 0x61, 0x74, 0x63, 0x68, 0x12,
	0x1e, 0x2e, 0x64, 0x62, 0x2e, 0x53, 0x65, 0x74, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x43, 0x6f, 0x6d,
	0x6d, 0x69, 0x74, 0x42, 0x61, 0x74, 0x63, 0x68, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x1f, 0x2e, 0x64, 0x62, 0x2e, 0x53, 0x65, 0x74, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x43, 0x6f, 0x6d,
	0x6d, 0x69, 0x74, 0x42, 0x61, 0x74, 0x63, 0x68, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x44, 0x0a, 0x0d, 0x53, 0x65, 0x74, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x41, 0x62, 0x6f, 0x72,
	0x74, 0x12, 0x18, 0x2e, 0x64, 0x62, 0x2e, 0x53, 0x65, 0x74, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x41,
	0x62, 0x6f, 0x72, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x19, 0x2e, 0x64, 0x62,
	0x2e, 0x53, 0x65, 0x74, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x41, 0x62, 0x6f, 0x72, 0x74, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x53, 0x0a, 0x12, 0x53, 0x65, 0x74, 0x45, 0x6e, 0x74,
	0x72, 0x79, 0x41, 0x62, 0x6f, 0x72, 0x74, 0x42, 0x61, 0x74, 0x63, 0x68, 0x12, 0x1d, 0x2e, 0x64,
	0x62, 0x2e, 0x53, 0x65, 0x74, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x41, 0x62, 0x6f, 0x72, 0x74, 0x42,
	0x61, 0x74, 0x63, 0x68, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1e, 0x2e, 0x64, 0x62,
	0x2e, 0x53, 0x65, 0x74, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x41, 0x62, 0x6f, 0x72, 0x74, 0x42, 0x61,
	0x74, 0x63, 0x68, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x35, 0x0a, 0x08, 0x47,
	0x65, 0x74, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x13, 0x2e, 0x64, 0x62, 0x2e, 0x47, 0x65, 0x74,
	0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x14, 0x2e, 0x64,
	0x62, 0x2e, 0x47, 0x65, 0x74, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x42, 0x10, 0x5a, 0x0e, 0x4a, 0x4b, 0x5a, 0x44, 0x42, 0x2f, 0x64, 0x62, 0x2f, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_db_proto_db_proto_rawDescOnce sync.Once
	file_db_proto_db_proto_rawDescData = file_db_proto_db_proto_rawDesc
)

func file_db_proto_db_proto_rawDescGZIP() []byte {
	file_db_proto_db_proto_rawDescOnce.Do(func() {
		file_db_proto_db_proto_rawDescData = protoimpl.X.CompressGZIP(file_db_proto_db_proto_rawDescData)
	})
	return file_db_proto_db_proto_rawDescData
}

var file_db_proto_db_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_db_proto_db_proto_goTypes = []interface{}{
	(*UpdateMap)(nil),                    // 0: db.UpdateMap
	(*SetEntryPrepareRequest)(nil),       // 1: db.SetEntryPrepareRequest
	(*SetEntryPrepareResponse)(nil),      // 2: db.SetEntryPrepareResponse
	(*SetEntryCommitRequest)(nil),        // 3: db.SetEntryCommitRequest
	(*SetEntryCommitResponse)(nil),       // 4: db.SetEntryCommitResponse
	(*SetEntryAbortRequest)(nil),         // 5: db.SetEntryAbortRequest
	(*SetEntryAbortResponse)(nil),        // 6: db.SetEntryAbortResponse
	(*SetEntryPrepareBatchRequest)(nil),  // 7: db.SetEntryPrepareBatchRequest
	(*SetEntryPrepareBatchResponse)(nil), // 8: db.SetEntryPrepareBatchResponse
	(*SetEntryCommitBatchRequest)(nil),   // 9: db.SetEntryCommitBatchRequest
	(*SetEntryCommitBatchResponse)(nil),  // 10: db.SetEntryCommitBatchResponse
	(*SetEntryAbortBatchRequest)(nil),    // 11: db.SetEntryAbortBatchRequest
	(*SetEntryAbortBatchResponse)(nil),   // 12: db.SetEntryAbortBatchResponse
	(*GetEntryRequest)(nil),              // 13: db.GetEntryRequest
	(*GetEntryResponse)(nil),             // 14: db.GetEntryResponse
	nil,                                  // 15: db.UpdateMap.UpdatesEntry
	nil,                                  // 16: db.SetEntryPrepareRequest.UpdatesEntry
	nil,                                  // 17: db.SetEntryCommitRequest.UpdatesEntry
}
var file_db_proto_db_proto_depIdxs = []int32{
	15, // 0: db.UpdateMap.updates:type_name -> db.UpdateMap.UpdatesEntry
	16, // 1: db.SetEntryPrepareRequest.updates:type_name -> db.SetEntryPrepareRequest.UpdatesEntry
	17, // 2: db.SetEntryCommitRequest.updates:type_name -> db.SetEntryCommitRequest.UpdatesEntry
	0,  // 3: db.SetEntryPrepareBatchRequest.updates:type_name -> db.UpdateMap
	0,  // 4: db.SetEntryCommitBatchRequest.updates:type_name -> db.UpdateMap
	1,  // 5: db.JKZDB.SetEntryPrepare:input_type -> db.SetEntryPrepareRequest
	7,  // 6: db.JKZDB.SetEntryPrepareBatch:input_type -> db.SetEntryPrepareBatchRequest
	3,  // 7: db.JKZDB.SetEntryCommit:input_type -> db.SetEntryCommitRequest
	9,  // 8: db.JKZDB.SetEntryCommitBatch:input_type -> db.SetEntryCommitBatchRequest
	5,  // 9: db.JKZDB.SetEntryAbort:input_type -> db.SetEntryAbortRequest
	11, // 10: db.JKZDB.SetEntryAbortBatch:input_type -> db.SetEntryAbortBatchRequest
	13, // 11: db.JKZDB.GetEntry:input_type -> db.GetEntryRequest
	2,  // 12: db.JKZDB.SetEntryPrepare:output_type -> db.SetEntryPrepareResponse
	8,  // 13: db.JKZDB.SetEntryPrepareBatch:output_type -> db.SetEntryPrepareBatchResponse
	4,  // 14: db.JKZDB.SetEntryCommit:output_type -> db.SetEntryCommitResponse
	10, // 15: db.JKZDB.SetEntryCommitBatch:output_type -> db.SetEntryCommitBatchResponse
	6,  // 16: db.JKZDB.SetEntryAbort:output_type -> db.SetEntryAbortResponse
	12, // 17: db.JKZDB.SetEntryAbortBatch:output_type -> db.SetEntryAbortBatchResponse
	14, // 18: db.JKZDB.GetEntry:output_type -> db.GetEntryResponse
	12, // [12:19] is the sub-list for method output_type
	5,  // [5:12] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_db_proto_db_proto_init() }
func file_db_proto_db_proto_init() {
	if File_db_proto_db_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_db_proto_db_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateMap); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_db_proto_db_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetEntryPrepareRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_db_proto_db_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetEntryPrepareResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_db_proto_db_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetEntryCommitRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_db_proto_db_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetEntryCommitResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_db_proto_db_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetEntryAbortRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_db_proto_db_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetEntryAbortResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_db_proto_db_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetEntryPrepareBatchRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_db_proto_db_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetEntryPrepareBatchResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_db_proto_db_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetEntryCommitBatchRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_db_proto_db_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetEntryCommitBatchResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_db_proto_db_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetEntryAbortBatchRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_db_proto_db_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetEntryAbortBatchResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_db_proto_db_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetEntryRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_db_proto_db_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetEntryResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_db_proto_db_proto_msgTypes[13].OneofWrappers = []interface{}{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_db_proto_db_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_db_proto_db_proto_goTypes,
		DependencyIndexes: file_db_proto_db_proto_depIdxs,
		MessageInfos:      file_db_proto_db_proto_msgTypes,
	}.Build()
	File_db_proto_db_proto = out.File
	file_db_proto_db_proto_rawDesc = nil
	file_db_proto_db_proto_goTypes = nil
	file_db_proto_db_proto_depIdxs = nil
}
