// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.19.4
// source: db/proto/db.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// JKZDBClient is the client API for JKZDB service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type JKZDBClient interface {
	SetEntryPrepare(ctx context.Context, in *SetEntryPrepareRequest, opts ...grpc.CallOption) (*SetEntryPrepareResponse, error)
	SetEntryPrepareBatch(ctx context.Context, in *SetEntryPrepareBatchRequest, opts ...grpc.CallOption) (*SetEntryPrepareBatchResponse, error)
	SetEntryCommit(ctx context.Context, in *SetEntryCommitRequest, opts ...grpc.CallOption) (*SetEntryCommitResponse, error)
	SetEntryCommitBatch(ctx context.Context, in *SetEntryCommitBatchRequest, opts ...grpc.CallOption) (*SetEntryCommitBatchResponse, error)
	SetEntryAbort(ctx context.Context, in *SetEntryAbortRequest, opts ...grpc.CallOption) (*SetEntryAbortResponse, error)
	SetEntryAbortBatch(ctx context.Context, in *SetEntryAbortBatchRequest, opts ...grpc.CallOption) (*SetEntryAbortBatchResponse, error)
	GetEntry(ctx context.Context, in *GetEntryRequest, opts ...grpc.CallOption) (*GetEntryResponse, error)
}

type jKZDBClient struct {
	cc grpc.ClientConnInterface
}

func NewJKZDBClient(cc grpc.ClientConnInterface) JKZDBClient {
	return &jKZDBClient{cc}
}

func (c *jKZDBClient) SetEntryPrepare(ctx context.Context, in *SetEntryPrepareRequest, opts ...grpc.CallOption) (*SetEntryPrepareResponse, error) {
	out := new(SetEntryPrepareResponse)
	err := c.cc.Invoke(ctx, "/db.JKZDB/SetEntryPrepare", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *jKZDBClient) SetEntryPrepareBatch(ctx context.Context, in *SetEntryPrepareBatchRequest, opts ...grpc.CallOption) (*SetEntryPrepareBatchResponse, error) {
	out := new(SetEntryPrepareBatchResponse)
	err := c.cc.Invoke(ctx, "/db.JKZDB/SetEntryPrepareBatch", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *jKZDBClient) SetEntryCommit(ctx context.Context, in *SetEntryCommitRequest, opts ...grpc.CallOption) (*SetEntryCommitResponse, error) {
	out := new(SetEntryCommitResponse)
	err := c.cc.Invoke(ctx, "/db.JKZDB/SetEntryCommit", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *jKZDBClient) SetEntryCommitBatch(ctx context.Context, in *SetEntryCommitBatchRequest, opts ...grpc.CallOption) (*SetEntryCommitBatchResponse, error) {
	out := new(SetEntryCommitBatchResponse)
	err := c.cc.Invoke(ctx, "/db.JKZDB/SetEntryCommitBatch", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *jKZDBClient) SetEntryAbort(ctx context.Context, in *SetEntryAbortRequest, opts ...grpc.CallOption) (*SetEntryAbortResponse, error) {
	out := new(SetEntryAbortResponse)
	err := c.cc.Invoke(ctx, "/db.JKZDB/SetEntryAbort", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *jKZDBClient) SetEntryAbortBatch(ctx context.Context, in *SetEntryAbortBatchRequest, opts ...grpc.CallOption) (*SetEntryAbortBatchResponse, error) {
	out := new(SetEntryAbortBatchResponse)
	err := c.cc.Invoke(ctx, "/db.JKZDB/SetEntryAbortBatch", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *jKZDBClient) GetEntry(ctx context.Context, in *GetEntryRequest, opts ...grpc.CallOption) (*GetEntryResponse, error) {
	out := new(GetEntryResponse)
	err := c.cc.Invoke(ctx, "/db.JKZDB/GetEntry", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// JKZDBServer is the server API for JKZDB service.
// All implementations must embed UnimplementedJKZDBServer
// for forward compatibility
type JKZDBServer interface {
	SetEntryPrepare(context.Context, *SetEntryPrepareRequest) (*SetEntryPrepareResponse, error)
	SetEntryPrepareBatch(context.Context, *SetEntryPrepareBatchRequest) (*SetEntryPrepareBatchResponse, error)
	SetEntryCommit(context.Context, *SetEntryCommitRequest) (*SetEntryCommitResponse, error)
	SetEntryCommitBatch(context.Context, *SetEntryCommitBatchRequest) (*SetEntryCommitBatchResponse, error)
	SetEntryAbort(context.Context, *SetEntryAbortRequest) (*SetEntryAbortResponse, error)
	SetEntryAbortBatch(context.Context, *SetEntryAbortBatchRequest) (*SetEntryAbortBatchResponse, error)
	GetEntry(context.Context, *GetEntryRequest) (*GetEntryResponse, error)
	mustEmbedUnimplementedJKZDBServer()
}

// UnimplementedJKZDBServer must be embedded to have forward compatible implementations.
type UnimplementedJKZDBServer struct {
}

func (UnimplementedJKZDBServer) SetEntryPrepare(context.Context, *SetEntryPrepareRequest) (*SetEntryPrepareResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetEntryPrepare not implemented")
}
func (UnimplementedJKZDBServer) SetEntryPrepareBatch(context.Context, *SetEntryPrepareBatchRequest) (*SetEntryPrepareBatchResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetEntryPrepareBatch not implemented")
}
func (UnimplementedJKZDBServer) SetEntryCommit(context.Context, *SetEntryCommitRequest) (*SetEntryCommitResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetEntryCommit not implemented")
}
func (UnimplementedJKZDBServer) SetEntryCommitBatch(context.Context, *SetEntryCommitBatchRequest) (*SetEntryCommitBatchResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetEntryCommitBatch not implemented")
}
func (UnimplementedJKZDBServer) SetEntryAbort(context.Context, *SetEntryAbortRequest) (*SetEntryAbortResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetEntryAbort not implemented")
}
func (UnimplementedJKZDBServer) SetEntryAbortBatch(context.Context, *SetEntryAbortBatchRequest) (*SetEntryAbortBatchResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetEntryAbortBatch not implemented")
}
func (UnimplementedJKZDBServer) GetEntry(context.Context, *GetEntryRequest) (*GetEntryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetEntry not implemented")
}
func (UnimplementedJKZDBServer) mustEmbedUnimplementedJKZDBServer() {}

// UnsafeJKZDBServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to JKZDBServer will
// result in compilation errors.
type UnsafeJKZDBServer interface {
	mustEmbedUnimplementedJKZDBServer()
}

func RegisterJKZDBServer(s grpc.ServiceRegistrar, srv JKZDBServer) {
	s.RegisterService(&JKZDB_ServiceDesc, srv)
}

func _JKZDB_SetEntryPrepare_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetEntryPrepareRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JKZDBServer).SetEntryPrepare(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/db.JKZDB/SetEntryPrepare",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JKZDBServer).SetEntryPrepare(ctx, req.(*SetEntryPrepareRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _JKZDB_SetEntryPrepareBatch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetEntryPrepareBatchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JKZDBServer).SetEntryPrepareBatch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/db.JKZDB/SetEntryPrepareBatch",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JKZDBServer).SetEntryPrepareBatch(ctx, req.(*SetEntryPrepareBatchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _JKZDB_SetEntryCommit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetEntryCommitRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JKZDBServer).SetEntryCommit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/db.JKZDB/SetEntryCommit",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JKZDBServer).SetEntryCommit(ctx, req.(*SetEntryCommitRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _JKZDB_SetEntryCommitBatch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetEntryCommitBatchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JKZDBServer).SetEntryCommitBatch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/db.JKZDB/SetEntryCommitBatch",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JKZDBServer).SetEntryCommitBatch(ctx, req.(*SetEntryCommitBatchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _JKZDB_SetEntryAbort_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetEntryAbortRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JKZDBServer).SetEntryAbort(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/db.JKZDB/SetEntryAbort",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JKZDBServer).SetEntryAbort(ctx, req.(*SetEntryAbortRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _JKZDB_SetEntryAbortBatch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetEntryAbortBatchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JKZDBServer).SetEntryAbortBatch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/db.JKZDB/SetEntryAbortBatch",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JKZDBServer).SetEntryAbortBatch(ctx, req.(*SetEntryAbortBatchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _JKZDB_GetEntry_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetEntryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JKZDBServer).GetEntry(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/db.JKZDB/GetEntry",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JKZDBServer).GetEntry(ctx, req.(*GetEntryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// JKZDB_ServiceDesc is the grpc.ServiceDesc for JKZDB service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var JKZDB_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "db.JKZDB",
	HandlerType: (*JKZDBServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SetEntryPrepare",
			Handler:    _JKZDB_SetEntryPrepare_Handler,
		},
		{
			MethodName: "SetEntryPrepareBatch",
			Handler:    _JKZDB_SetEntryPrepareBatch_Handler,
		},
		{
			MethodName: "SetEntryCommit",
			Handler:    _JKZDB_SetEntryCommit_Handler,
		},
		{
			MethodName: "SetEntryCommitBatch",
			Handler:    _JKZDB_SetEntryCommitBatch_Handler,
		},
		{
			MethodName: "SetEntryAbort",
			Handler:    _JKZDB_SetEntryAbort_Handler,
		},
		{
			MethodName: "SetEntryAbortBatch",
			Handler:    _JKZDB_SetEntryAbortBatch_Handler,
		},
		{
			MethodName: "GetEntry",
			Handler:    _JKZDB_GetEntry_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "db/proto/db.proto",
}
